import { redirect } from 'next/navigation';
import { getCurrentUser } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import AdminShell from '@/components/admin-shell';
import RecordsTable from '@/components/admin/records-table';
import { ruPlace, ruStatus, ruTransmission } from '@/lib/data';
import { syncCompletedBookings } from '@/lib/booking-status';
export const dynamic='force-dynamic';
export default async function AdminRecordsPage({ searchParams }: { searchParams: Promise<{ city?: string }> }){const user=await getCurrentUser();if(!user||!['ADMIN','MANAGER'].includes(user.role))redirect('/login');const params=await searchParams;const citySlug=user.role==='MANAGER'?(await prisma.city.findUnique({where:{id:user.cityId||''}}))?.slug:params.city;if(!citySlug)redirect('/admin/select-city');const city=await prisma.city.findUnique({where:{slug:citySlug}});if(!city)redirect('/admin/select-city');await syncCompletedBookings(city.id);const bookings=await prisma.booking.findMany({where:{cityId:city.id},include:{user:true,instructor:true,car:true},orderBy:[{date:'desc'},{startHour:'desc'}]});const instructors=await prisma.instructor.findMany({where:{cityId:city.id},orderBy:{firstName:'asc'}});const cars=await prisma.car.findMany({where:{cityId:city.id},orderBy:{name:'asc'}});return <AdminShell citySlug={citySlug} currentPath="/admin"><div className="mb-7"><div className="eyebrow">{city.name}</div><h1 className="mt-2 text-3xl font-semibold">Записи</h1><p className="muted mt-2 text-sm">Все записи выбранного города. Новую запись создаёт клиент через публичный сайт.</p></div><RecordsTable city={citySlug} initial={bookings.map(b=>({id:b.id,name:`${b.user.firstName} ${b.user.lastName}`,phone:b.user.phone,date:b.date.toISOString().slice(0,10),startHour:b.startHour,endHour:b.endHour,duration:b.endHour-b.startHour,instructor:`${b.instructor.firstName} ${b.instructor.lastName}`,instructorId:b.instructorId,car:b.car.name,carId:b.carId,transmission:b.transmission,place:b.place,hourlyPrice:b.hourlyPrice,totalPrice:b.totalPrice,status:b.status}))} instructors={instructors.map(i=>({id:i.id,name:`${i.firstName} ${i.lastName}`}))} cars={cars.map(c=>({id:c.id,name:c.name,transmission:c.transmission}))}/></AdminShell>}
