import Link from 'next/link';
import { ArrowRight, CalendarDays, CheckCircle2, MapPin, ShieldCheck, Sparkles } from 'lucide-react';
import SiteHeader from '@/components/site-header';
import Footer from '@/components/footer';
import SectionTitle from '@/components/section-title';
import FAQ from '@/components/faq';
import { cities } from '@/lib/data';

export default function HomePage() {
  return <div className="min-h-screen"><SiteHeader/><main>
    <section className="container-x pt-6 sm:pt-10"><div className="relative min-h-[620px] overflow-hidden rounded-[2rem] bg-neutral-950 text-white shadow-2xl sm:min-h-[680px]"><img src="https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=2000&q=88" alt="Автомобиль Autonur" className="absolute inset-0 h-full w-full object-cover opacity-60"/><div className="absolute inset-0 bg-gradient-to-r from-black via-black/65 to-black/15"/><div className="hero-noise absolute inset-0 opacity-30"/><div className="relative flex min-h-[620px] flex-col justify-end p-6 sm:min-h-[680px] sm:p-10 lg:p-14"><div className="max-w-2xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-2 text-xs backdrop-blur"><Sparkles size={14} className="text-orange-300"/> Практика без лишнего</div><h1 className="text-5xl font-semibold leading-[.98] tracking-tight sm:text-6xl lg:text-8xl">Научись водить уверенно</h1><p className="mt-6 max-w-xl text-base leading-7 text-white/75 sm:text-lg">Практические занятия с профессиональными инструкторами Autonur.</p><Link href="#cities" className="mt-8 inline-flex items-center gap-2 rounded-full bg-orange-500 px-6 py-3.5 text-sm font-semibold text-white transition hover:bg-orange-600">Выбрать город <ArrowRight size={17}/></Link></div></div></div></section>
    <section id="advantages" className="section"><div className="container-x"><SectionTitle eyebrow="Почему Autonur" title="Всё, что нужно для спокойной практики"/><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Профессиональные инструкторы','Опытные специалисты, которые помогают без лишнего давления.',ShieldCheck],['Свободное время','Показываем только доступные слоты, чтобы вы не теряли время.',CalendarDays],['3 города','Астана, Кокшетау и Караганда — выбирайте удобную локацию.',MapPin],['Прозрачная цена','Стоимость рассчитывается по выбранному инструктору, месту и длительности.',CheckCircle2]].map(([title,text,Icon])=>{const I=Icon as typeof ShieldCheck;return <div key={String(title)} className="surface p-6"><div className="grid h-10 w-10 place-items-center rounded-xl bg-orange-100 text-orange-600 dark:bg-orange-950/30 dark:text-orange-300"><I size={19}/></div><h3 className="mt-5 font-semibold">{String(title)}</h3><p className="muted mt-2 text-sm leading-6">{String(text)}</p></div>})}</div></div></section>
    <section id="steps" className="section bg-white/60 dark:bg-white/[.02]"><div className="container-x"><SectionTitle eyebrow="Как проходят занятия" title="Четыре шага до первой практики"/><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[['01','Коробка','Автомат или механика.'],['02','Дата и время','Выбираете только свободные часы.'],['03','Инструктор и автомобиль','Система покажет совместимые варианты.'],['04','Подтверждение','Менеджер вашего города уточнит оплату.']].map(([n,t,d])=><div key={n} className="relative rounded-3xl border border-black/5 bg-[#f7f6f3] p-6 dark:border-white/10 dark:bg-neutral-950"><span className="text-sm font-semibold text-orange-500">{n}</span><h3 className="mt-9 text-lg font-semibold">{t}</h3><p className="muted mt-2 text-sm leading-6">{d}</p></div>)}</div></div></section>
    <section id="cities" className="section"><div className="container-x"><SectionTitle eyebrow="Ваш город" title="Выберите город" description="После выбора откроется страница только с информацией, расписанием и контактами этого города."/><div className="mt-10 grid gap-4 lg:grid-cols-3">{cities.map(c=><Link key={c.slug} href={`/${c.slug}`} className="group surface relative min-h-[360px] overflow-hidden"><img src={c.hero} alt={c.name} className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black via-black/20 to-transparent"/><div className="relative flex h-full flex-col justify-end p-6 text-white"><div className="text-sm text-white/65">Autonur</div><div className="mt-1 flex items-end justify-between gap-4"><h3 className="text-2xl font-semibold">{c.name}</h3><span className="grid h-10 w-10 place-items-center rounded-full bg-white/10 backdrop-blur transition group-hover:bg-orange-500"><ArrowRight size={17}/></span></div></div></Link>)}</div></div></section>
    <section id="faq" className="section bg-white/60 dark:bg-white/[.02]"><div className="container-x grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><SectionTitle eyebrow="FAQ" title="Частые вопросы" description="Простые ответы на организационные вопросы перед записью."/><FAQ/></div></section>
    <section id="contacts" className="section"><div className="container-x"><div className="surface flex flex-col gap-7 bg-neutral-950 p-7 text-white sm:p-10 lg:flex-row lg:items-center lg:justify-between"><div><div className="eyebrow text-orange-400">Контакты</div><h2 className="mt-3 text-3xl font-semibold">Есть вопросы?</h2><p className="mt-3 max-w-xl text-white/65">Выберите город на сайте, чтобы получить его контакт менеджера. Instagram общий для всех городов.</p></div><div className="flex flex-wrap items-center gap-3"><Link href="#cities" className="inline-flex w-fit items-center gap-2 rounded-full bg-orange-500 px-5 py-3 text-sm font-semibold">Выбрать город <ArrowRight size={16}/></Link><a href="https://instagram.com/autonur" target="_blank" rel="noreferrer" className="inline-flex w-fit items-center gap-2 rounded-full border border-white/15 px-5 py-3 text-sm font-semibold">Instagram</a></div></div></div></section>
  </main><Footer/></div>;
}
