'use client';
import { useState, FormEvent } from 'react';
import { useRouter } from 'next/navigation';
export default function ForgotForm() {
  const [phone, setPhone] = useState(''); const [requested, setRequested] = useState(false); const [error, setError] = useState(''); const [code, setCode] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [busy, setBusy] = useState(false); const router = useRouter();
  async function requestCode(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); const r = await fetch('/api/recovery/request', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ phone }) }); const d = await r.json(); if (!r.ok) setError(d.error || 'Ошибка.'); else setRequested(true); setBusy(false); }
  async function reset(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); const r = await fetch('/api/recovery/reset', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ phone, code, password, confirmPassword }) }); const d = await r.json(); if (!r.ok) { setError(d.error || 'Ошибка.'); setBusy(false); return; } router.push(d.next); router.refresh(); }
  if (!requested) return <form onSubmit={requestCode} className="space-y-4"><Field label="Телефон" value={phone} onChange={setPhone} placeholder="+7 700 000 00 00"/>{error && <Error text={error}/>}<button disabled={busy} className="focus-ring w-full rounded-full bg-orange-500 px-5 py-3.5 text-sm font-semibold text-white">{busy ? 'Проверяем…' : 'Продолжить'}</button><p className="muted text-sm leading-6">Вы вводите номер только для поиска аккаунта. Код создаёт менеджер вашего города и передаёт его вам.</p></form>;
  return <form onSubmit={reset} className="space-y-4"><div className="rounded-2xl bg-orange-50 p-4 text-sm leading-6 text-orange-900 dark:bg-orange-950/20 dark:text-orange-200">Обратитесь к менеджеру вашего города и получите одноразовый код восстановления.</div><Field label="Код восстановления" value={code} onChange={setCode} placeholder="6 цифр"/><Field label="Новый пароль" value={password} onChange={setPassword} type="password"/><Field label="Подтвердите пароль" value={confirmPassword} onChange={setConfirmPassword} type="password"/>{error && <Error text={error}/>}<button disabled={busy} className="focus-ring w-full rounded-full bg-orange-500 px-5 py-3.5 text-sm font-semibold text-white">{busy ? 'Сохраняем…' : 'Сменить пароль'}</button></form>;
}
function Field({label,value,onChange,type='text',placeholder='' }:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder?:string}){return <label className="block"><span className="mb-2 block text-sm font-medium">{label}</span><input required value={value} onChange={e=>onChange(e.target.value)} type={type} placeholder={placeholder} className="focus-ring w-full rounded-2xl border border-black/10 bg-white px-4 py-3.5 dark:border-white/10 dark:bg-neutral-900"/></label>}
function Error({text}:{text:string}){return <div role="alert" className="rounded-2xl bg-red-50 p-4 text-sm text-red-700 dark:bg-red-950/25 dark:text-red-300">{text}</div>}
