import { redirect } from 'next/navigation';
import { getCurrentUser } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import AdminShell from '@/components/admin-shell';
import ReadTable from '@/components/admin/read-table';
import RecoveryButton from '@/components/admin/recovery-button';
import PhoneChangeButton from '@/components/admin/phone-change-button';
import { ruStatus } from '@/lib/data';
export const dynamic='force-dynamic';
export default async function UsersPage({searchParams}:{searchParams:Promise<{city?:string}>}){const user=await getCurrentUser();if(!user||!['ADMIN','MANAGER'].includes(user.role))redirect('/login');const p=await searchParams;const citySlug=user.role==='MANAGER'?(await prisma.city.findUnique({where:{id:user.cityId||''}}))?.slug:p.city;if(!citySlug)redirect('/admin/select-city');const city=await prisma.city.findUnique({where:{slug:citySlug}});if(!city)redirect('/admin/select-city');const users=await prisma.user.findMany({where:{cityId:city.id,role:'USER'},include:{bookings:{orderBy:[{date:'desc'},{startHour:'desc'}],include:{city:true,instructor:true,car:true}}},orderBy:{firstName:'asc'}});return <AdminShell citySlug={citySlug} currentPath="/admin/users"><div className="mb-7"><div className="eyebrow">{city.name}</div><h1 className="mt-2 text-3xl font-semibold">Пользователи</h1><p className="muted mt-2 text-sm">Просмотр данных и истории. Пароли никогда не отображаются.</p></div><ReadTable headers={['Имя','Телефон','История записей','Статус','Действия']} rows={users.map(u=>[<span className="font-medium">{u.firstName} {u.lastName}</span>,<a className="text-orange-600" href={`tel:${u.phone.replace(/\D/g,'')}`}>{u.phone}</a>,u.bookings.length?<div className="max-w-[430px] space-y-1 text-xs">{u.bookings.map(b=><div key={b.id}>{b.date.toISOString().slice(0,10)} · {String(b.startHour).padStart(2,'0')}:00–{String(b.endHour).padStart(2,'0')}:00 · {b.city.name} · {b.instructor.firstName} {b.instructor.lastName} · {b.car.name}</div>)}</div>:'—',u.bookings[0]?ruStatus(u.bookings[0].status):'—',<div className="flex flex-wrap gap-2">{user.role==='MANAGER'&&<RecoveryButton userId={u.id}/>} {user.role==='MANAGER'&&<PhoneChangeButton userId={u.id} current={u.phone} city={citySlug}/>}</div>])}/></AdminShell>}
